[package]
name = "schemers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cc = "1.0.72"
tree-sitter-graph = "0.2.0"
rustyline = "9.0.0"
